data:
  #args forwarded (linked) to model
  dataset_name: "ww3"
  num_input_steps: 1
  num_pred_steps_train: 1
  num_pred_steps_val_test: 1
  batch_size: 1

  #other args
  num_workers: 10
  prefetch_factor: null
  pin_memory: False 
  dataset_conf: "config/datasets/ww3.json"
  predict_conf: null